server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cwm1028.
    url: jdbc:mysql://localhost:3306/test_demo

mybatis:
  type-aliases-package: com.example.demo3.pojo
